spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      default_schema: picpaychallenge

springdoc:
  swagger-ui:
    path: /swagger-ui.html